### ISSUE TITLE
Duplicate Schedule

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#80] opened 2024-02-13 12:27 UTC
Hi Gareth,

for some reason, one of my backups (I have 2), is now scheduled to run twice at the same time:
![image](https://github.com/garethgeorge/backrest/assets/62859/3fa79717-8f81-4d64-82da-fd0367d7b9f5)

My backup configuration in the json file is the following:
```
    {
      "id": "Backup",
      "repo": "Backup_Repo",
      "paths": [
        "/raid/2Backup"
      ],
      "excludes": [],
      "cron": "0 11 * * *",
      "retention": {
        "maxUnusedLimit": "",
        "keepLastN": 7,
        "keepHourly": 0,
        "keepDaily": 0,
        "keepWeekly": 0,
        "keepMonthly": 0,
        "keepYearly": 0,
        "keepWithinDuration": ""
      },
      "hooks": []
    },
```

Any idea why it happened?

**Comment by modem** [comment] 2024-02-13 12:33
After editing the plan, the proper schedule has been set, but maybe its worth to understand what happened for all of the sudden there's a double schedule

**Comment by garethgeorge** [comment] 2024-02-14 18:53
This may be a UI only issue -- did the duplicate entry go away when refreshing the UI?

**Comment by modem** [comment] 2024-02-14 18:59
No, it did not go away with refresh, and as you can see on the picture attached initially, on the 13th, the 2nd backup ran right after the 1st one finished.

**Comment by garethgeorge** [comment] 2024-02-14 19:51
Ah, I see now. Just to make sure i'm understanding: it looks like it's reproducibly scheduling two backup runs instead of one?

That's really strange behavior. Does it persist after restarting backrest as well?

**Comment by modem** [comment] 2024-02-14 21:19
I don't think I restarted the container while I faced the issue. I've searched for `Starting web server :9898` and only found 1 entry for a server reboot I've done today.
And I don't know how to reproduce this.

**Comment by modem** [comment] 2024-02-15 11:43
I've just seen this issue again.
I noticed that when today's backup started, the tomorrow schedule was already there, and when the backup finished, it scheduled the 2nd time for tomorrow.
And I confirm that the duplication clears with the container restart.

**Comment by garethgeorge** [comment] 2024-02-18 07:10
Just to update on this, I've not yet been able to reproduce (I'm carefully watching my installations to see if I observe this). Out of curiosity, is your device a laptop that suspends / resumes from sleep (asking because I'm exclusively running on desktop hardware at the moment).

Still very interested to see any logs that might reveal details.

**Comment by modem** [comment] 2024-02-18 15:38
I'm running it on a QNAP NAS that is running 24/7.

**Comment by garethgeorge** [comment] 2024-02-21 23:35
I've now been able to reproduce. I've not seen backups running twice, but I am seeing multiple entries for a single scheduled backup in the log. In particular, additional entries seem to be created with an "UNDEFINED" status, it feels a bit like a single backup operation getting recorded multiple times in weird cases. 

I'll spend some time writing new test coverage to try to pin down where this is happening. I'll be out most of this weekend but you can hopefully expect some progress on this late next week. At the moment, I don't think there's any risk to data from this bug.

**Comment by garethgeorge** [comment] 2024-03-30 23:34
This should be fixed in the latest release, the root cause was much simpler than any of my suspicions. 

I believe that operations were occasionally being duplicated if the config was updated during a long running backup operation.

**Closed by garethgeorge** 2024-03-30 23:35 UTC
Labels: bug, p1
