### ISSUE TITLE
Check Integrity

### ISSUE THREAD

**Issue by marcschuler** [garethgeorge/backrest#293] opened 2024-05-23 18:14 UTC
Restic has a feature to check the integrity of backups. This is useful because you can't 100% trust a repository: Hard Drives can deteriorate or files could be deleted by accident.

It would be nice to have a "Check Files" button next to "Backup now" which checks the files using "rclone check".

Additionally it would be nice if the user could define a cronjob to automatically run check the files every x days.

**Comment by garethgeorge** [comment] 2024-05-24 21:37
Hey, this is currently one of the highest items on the todo list for the next minor version. Duplicate of https://github.com/garethgeorge/backrest/issues/75 . Definitely something that's planned :)

In the mean time you can use "Run Command" to run a check manually.

**Closed** 2024-05-25 01:19 UTC
Labels: duplicate, enhancement
