### ISSUE TITLE
Restored files are missing when suggested restore path is used

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#364] opened 2024-07-01 08:58 UTC
When restoring a folder, if the proposed path is accepted, the restored files and folders cannot be found on that path.
Inside the container, I can find them under `/root/Downloads/` directory inside the container, probably due to the new download function.
I see this as the restore result in Backrest interface:
![image](https://github.com/garethgeorge/backrest/assets/62859/0d07f76b-75b8-4628-85ff-669ab5243ede)

If I customize the path where the restore will be stored, the restore works as expected, and the path shown in Backrest interface is the desired one.
![image](https://github.com/garethgeorge/backrest/assets/62859/85a26935-9e70-421e-ad97-6eb03be83406)

It seems that if the restore path is accepted by default, Backrest is adds `/root/Downloads/` to the suggested path

**To Reproduce**

1. Go to a plan
2. Try to restore something
3. Accept the default path suggested in the restore window
4. Start the restore
5. Once restore search for the target path on the disk and notice it's missing

**Expected behavior**
Expecting to find the restore files and folders on the proposed path.

**Platform Info**

- OS and Architecture Docker
- Backrest Version 1.2.0

**Comment by garethgeorge** [comment] 2024-07-01 18:37
Is the suggestion essentially that inferring a downloads directory e.g. `/root/Downloads` is a bad default? 

Would defaulting to a subfolder of the original location of the files be a more expected behavior? Open to community feedback on the right default here.

**Comment by modem** [comment] 2024-07-01 18:47
For me, the suggestion starts with `/raid/` so I would expect to see the restored files there, not under `/root/Download/`.
And in case of Docker, usually the root folder is not mapped on the host, so the files are restored inside the container.
And in case we specify the restore folder, they are properly restored on the expected path, which I find inconsistent and confusing.

**Comment by garethgeorge** [comment] 2024-07-01 19:00
Ah, thanks for filing this. That's definitely unintended, looks like there's some bug going on with the form submission -- the target path isn't actually getting to the request made to the backend. I'll get a patch release out this week addressing this.

**Comment by garethgeorge** [comment] 2024-07-02 06:03
Partially fixed in a patch release tonight, noticed after I pushed that there's still a more minor bug: the initially populated value isn't respected, restore path will still default to downloads. You must enter an explicit path to restore to a custom location. 

Will put out another patch release combined with the hook refactoring I'm working on to followup on this later in the week.

**Comment by stefanomarty** [comment] 2024-07-07 14:46
I added the /root/Downloads path to docker-compose.yml to get the restored files on the server (outside the Docker container) and it works fine. I have just a couple of question:
1. Is the '/root/Downloads' path configurable? I cannot find it in the config.
2. Is it possible to delete the restore operation record from the Operation Lists once the restored files are used and consumed? I mean, if I move or delete the files from their position in /root/Downloads/... a subsequent click on the 'Download file(s)' link in the Operation List window throws an error. It would help to be able to delete that specific restore operation record from the list.

**Comment by garethgeorge** [comment] 2024-07-10 22:17
In the next release my plan is to split restore operations into a new entry in the operation history and have their title include the snapshot they relate to. This way the restore operations can also be deleted directly when you've removed the files they depend on -- agreed that it'd also be neat to have some mechanism to show whether or not the files are still available. 

I'll give that some thought as a UI improvement.

**Comment by garethgeorge** [comment] 2024-08-15 04:25
I think this is resolved in the last few releases! Feel free to give a ping if you're still running into a problem here, marking as resolved for now.

**Closed by garethgeorge** 2024-08-15 04:25 UTC
Labels: bug, p1
